import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/header/header";
import JsonData from "@/data/data.json"
import Navigation from "@/app/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const headerData = JSON.stringify( JsonData.Header );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navigation/>
        <Header data={headerData}/>
        {children}
      </body>
    </html>
  );
}
